# Generated by Django 4.0.5 on 2022-06-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_year', models.CharField(max_length=255)),
                ('acquired', models.BooleanField(default=True)),
                ('thumbnail', models.TextField(blank=True)),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.author')),
            ],
        ),
    ]
