# Generated by Django 4.0.6 on 2022-07-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_authors_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
