# Generated by Django 4.0.6 on 2022-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
